version: 2

jobs:
  test:
    docker:
      - image: node:10.15.1
    working_directory: /repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
      - run:
          name: Codecov
          command: yarn run codecov

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
